# Generated by Django 6.0.5 on 2026-07-11 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numperiodo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percepciones', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deducciones', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='empleados.empleados')),
            ],
        ),
    ]
