# Generated by Django 6.0.5 on 2026-07-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('apellido', models.CharField()),
                ('telefono', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('turno', models.CharField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
