# Generated by Django 6.0.5 on 2026-07-12 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='grupos_usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('empleado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.empleados')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grupos.grupos_grupos')),
            ],
        ),
    ]
