# Generated by Django 6.0.5 on 2026-07-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos_usuarios',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
