# Generated by Django 6.0.5 on 2026-07-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
