# Generated by Django 6.0.5 on 2026-07-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField()),
                ('fecha', models.DateField()),
                ('subtotal', models.FloatField()),
                ('iva', models.FloatField()),
                ('total', models.FloatField()),
                ('producto', models.ManyToManyField(to='productos.producto')),
                ('proveedor', models.ManyToManyField(to='proveedores.proveedores')),
            ],
        ),
    ]
