# Generated by Django 6.0.5 on 2026-06-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('direccion', models.CharField()),
                ('telefono', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('categoria', models.CharField()),
            ],
        ),
    ]
